#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "Usage: ensure-link-packages   [--help]"
  echo "Ensures that the current folder is linked to the packages folder"
  exit 0
fi

link-packages ./packages ./
git diff --quiet || {
  echo "Error: Uncommitted changes detected after running ensure-link."
  exit 1
}
git diff
