#!/bin/bash

if [[ " $@ " == *" --help "* ]]; then
  echo "Usage: fence <...text> [--help]"
  echo "This creates a fence block"
  exit 0
fi

echo "+----------------------------------------------------------------------+"
for arg in "$@"; do
  printf "| %-68s |\n" "$arg"
done
echo "+----------------------------------------------------------------------+"
