#!/bin/bash

if [ "$1" == "--help" ]; then
  echo "Usage: link-this [--help]"
  echo "Links all packages in the ./packages directory to the current directory."
  exit 0
fi

link-packages ./packages ./
