name: Run Ensure Commands

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add repository to PATH
      run: echo "$(pwd)/bin" >> $GITHUB_PATH

    - name: Run ensure-shebang script
      run: ensure-shebang

    - name: Run ensure-usage script
      run: ensure-usage

    - name: Run ensure-exec script
      run: ensure-exec

    - name: Run ensure-help script
      run: ensure-help

    - name: Run ensure-link script
      run: ensure-link-this
        
